# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Veracode SCA Agent Scan

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_scan:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: List of the GitHub Actions environment variables on Ubuntu
      run: env

    - name: SCA Agent Scan
      # set APPLICATION_NAME to the repository name without the owner prepended
      # echo ${{ github.repository }} | cut -d'/' -f2
      # export ${{ env.APPLICATION_NAME }}=`echo ${{ github.repository }} | cut -d'/' -f2`
      run: |
           export SRCCLR_API_TOKEN='${{ secrets.SRCCLR_API_TOKEN }}'
           echo "${{ github.repository }} | cut -d'/' -f2" >> $env.APPLICATION_NAME
           echo ${{ env.APPLICATION_NAME }}
      # curl -sSL https://download.sourceclear.com/ci.sh | bash -s – scan --debug --scm-uri 'https://NodeGoat' --scm-ref master --scm-ref-type branch
