# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Veracode Upload & Scan

on:
  workflow_dispatch:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build_and_scan:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [12.x, 14.x, 16.x]
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

    - name: Zip Release
      # You may pin to the exact commit or the version.
      # uses: TheDoctor0/zip-release@09336613be18a8208dfa66bd57efafd9e2685657
      uses: TheDoctor0/zip-release@0.6.2
      with:
        # Filename for archive
        #filename: # default is release.zip
        # Base path for archive files
        #path: # optional, default is .
        # Working directory before zipping
        #directory: # optional, default is .
        # List of excluded files / directories
        exclusions: '/test/* /config/* *.circleci/* *.git* /*node_modules/* .editorconfig .dockerignore' 
        # List of excluded files / directories with recursive wildcards (only applies on Windows with `zip` type)
        #recursive_exclusions: # optional, default is 
        # Tool to use for archiving
        #type: # optional, default is zip

    - name: Veracode Upload And Scan
      # You may pin to the exact commit or the version.
      # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
      uses: veracode/veracode-uploadandscan-action@0.2.1
      with:
        # appname
        # appname: # default is ${{ github.repository }}
        # createprofile
        # createprofile: # default is true
        # filepath
        filepath: release.zip
        # version
        # version: # default is Scan from Github job: ${{ github.run_id }}
        # vid
        vid: '${{ secrets.VERACODE_API_ID }}'
        # vkey
        vkey: '${{ secrets.VERACODE_API_KEY }}'
        # true or flase
        createsandbox: true # optional
        # name of the sandbox
        sandboxname: Github # optional
